### ISSUE TITLE
Unable to run on iOS

### ISSUE THREAD

**Issue by richardtop** [edwinbosire/Urbandict#1]
Hello, thanks for the work you've done.
Unfortunately I'm unable to run it, I get this error:
```
Found Xcode project Urban Dict.xcodeproj
Launching iPhone 6 (iOS 10.3)...
Building using "xcodebuild -project Urban Dict.xcodeproj -configuration Debug -scheme Urban Dict -destination id=A7747915-90EA-4CCC-9182-A61FF648B6A0 -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/richard/Documents/Code/Urbandict/ios/build


xcodebuild: error: The project named "Urban Dict" does not contain a scheme named "Urban Dict". The "-list" option can be used to find the names of the schemes in the project.

Installing build/Build/Products/Debug-iphonesimulator/Urban Dict.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Urban Dict.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by edwinbosire** [comment]
Try running the program from xCode,

`xcodebuild -project Urban Dict.xcodeproj -configuration Debug -scheme Urban Dict -destination id=A7747915-90EA-4CCC-9182-A61FF648B6A0 -derivedDataPath build`

There's a clear problem here, the -scheme named Urban Dict does not exist, only UrbanDictionary

Run the following command within the /ios project directory of the project

`xcodebuild -list` 

You'll see that under Schemes: only UrbanDictionary exists.

**Comment by richardtop** [comment]
@edwinbosire thanks, launching an Xcode project helps.
Is there a way to change scheme name (to `UrbanDictionary `) so running command `react-native run-ios` will work as well?

**Comment by edwinbosire** [comment]
@richardtop try this

`$ react-native run-ios --scheme UrbanDictionary`

This has not been tested. Check this [commit](https://github.com/facebook/react-native/commit/8b55e50d1da91dbeadddd7a5a40cc6e4532f9551) for a reference to scheme pertaining to our issue

Hope this helps. I'll close this issue for now.

**Comment by richardtop** [comment]
@edwinbosire Thanks for the help and great example app!
